/* empty css                      */import{g as f,S as h,a as g,N as w,P as v}from"./assets/vendor-i9_4bIE2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();f.registerPlugin(h);document.addEventListener("DOMContentLoaded",()=>{f.timeline({scrollTrigger:{trigger:".progression",start:"top 75%",toggleActions:"play none none none",once:!0}}).to(".fill-1",{width:"92%",duration:.7,ease:"power2.out"}).to(".fill-2",{width:"82%",duration:.7,ease:"power2.out"},"-=0.45").to(".fill-3",{width:"70%",duration:.7,ease:"power2.out"},"-=0.45").to(".fill-4",{width:"60%",duration:.7,ease:"power2.out"},"-=0.45").to(".fill-5",{width:"42%",duration:.7,ease:"power2.out"},"-=0.45").to(".progression-dot",{opacity:1,duration:.3,stagger:.08},"-=0.5")});g.use([w,v]);function y(n){if(!n)return;n.destroy(!0,!0);const e=n.el;e==null||e.removeAttribute("style");const s=e==null?void 0:e.querySelector(".swiper-wrapper");s==null||s.removeAttribute("style"),e==null||e.querySelectorAll(".swiper-slide").forEach(l=>{l.removeAttribute("style")})}function m({rootSelector:n,prevEl:e,nextEl:s,paginationEl:l}){const t=document.querySelector(n);if(!t)return;const o=t.querySelector(".swiper");if(!o)return;let i=null;const r=window.matchMedia("(min-width: 1440px)"),c=()=>{i||(i=new g(o,{slidesPerView:1,spaceBetween:16,speed:450,loop:!1,grabCursor:!0,navigation:{prevEl:e,nextEl:s},pagination:{el:l,clickable:!0,type:"bullets"}}))},a=()=>{i&&(y(i),i=null)},d=()=>{r.matches?a():c()};d();const u=()=>d();r.addEventListener?r.addEventListener("change",u):r.addListener(u)}m({rootSelector:".features-swiper",prevEl:".features-prev",nextEl:".features-next",paginationEl:".features-pagination"});m({rootSelector:".gallery-swiper",prevEl:".gallery-prev",nextEl:".gallery-next",paginationEl:".gallery-pagination"});document.querySelectorAll(".faq-acc-el-trigger").forEach(n=>{n.addEventListener("click",()=>{const e=n.closest(".faq-acc-el"),s=e.querySelector(".faq-acc-el-descr-frame"),l=n.querySelector("svg"),t=e.classList.contains("open"),o=`
<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.5 6H9.5" stroke="#475569" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M6 2.5V9.5" stroke="#475569" stroke-linecap="round" stroke-linejoin="round" />
</svg>`,i=`
<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.5 6H9.5" stroke="#00C8FF" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;t?(e.classList.remove("open"),s.style.maxHeight="0",l.outerHTML=o):(e.classList.add("open"),s.style.maxHeight=s.scrollHeight+"px",l.outerHTML=i)})});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),e=n.querySelector(".icon"),s=document.querySelector(".modal"),l=document.querySelectorAll(".menu-list-item"),t=document.querySelector(".header");let o=!1;const i=`
<svg width="31" height="31" viewBox="0 0 31 31" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.16699 15.5H25.8337" stroke="#90A1B9" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.16699 7.75H25.8337" stroke="#90A1B9" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
  <path d="M5.16699 23.25H25.8337" stroke="#90A1B9" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `,r=`
<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M28.3333 28.3333L1 1M28.3333 1L1 28.3333" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>
    `;n.addEventListener("click",()=>{o=!o,e.innerHTML=o?r:i,o?c():a()}),l.forEach(u=>u.addEventListener("click",()=>{a(),e.innerHTML=i,o=!1})),window.addEventListener("scroll",d);function c(){s.style.display="block"}function a(){s.style.display="none"}function d(){t&&(window.scrollY>60?t.classList.add("header-scroll"):t.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const r=document.getElementById("site-header");return r?r.offsetHeight:0}function e(r){const c=document.getElementById(r);if(!c)return;const a=n(),d=c.getBoundingClientRect().top+window.pageYOffset-a;window.scrollTo({top:d,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(r=>{r.addEventListener("click",function(c){const a=this.getAttribute("href");if(!a)return;const[d,u]=a.split("#");if(!u)return;const p=window.location.pathname.split("/").pop();!(d===""||d==="./"||d===p||d==="./"+p)||!document.getElementById(u)||(c.preventDefault(),e(u),o(u))})});const l=document.querySelectorAll("section[id]"),t=document.querySelectorAll(".navigation-item");function o(r){t.forEach(a=>a.classList.remove("active"));const c=document.querySelector(`.navigation-item a[href*="#${r}"]`);c&&c.closest(".navigation-item").classList.add("active")}function i(){const r=window.pageYOffset+n()+100;l.forEach(c=>{const a=c.offsetTop,d=a+c.offsetHeight;r>=a&&r<d&&o(c.id)})}if(window.addEventListener("scroll",i),window.location.hash){const r=window.location.hash.substring(1);setTimeout(()=>{e(r),o(r)},300)}});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),e=document.getElementById("accept-cookies"),s=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),e.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});
//# sourceMappingURL=index.js.map
